apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kuberay-operator-leader-election
sub
- kind: ServiceAccount
  name: kuberay-operator
